name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-release:
    permissions: write-all
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      dist-name: ESurfingPy-CLI
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-11.0]
        python-version: ['3.10']

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Check out
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install nuitka ordered-set zstandard

    - name: Build
      run: python build.py

    - name: Package
      working-directory: dist
      run: tar -zcvf ../${{ env.dist-name }}_${{ matrix.os }}.tar.gz -c ./*

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }} Build
        path: ${{ env.dist-name }}_${{ matrix.os }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.dist-name }}_${{ matrix.os }}.tar.gz
